version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  test:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/repo

    steps:        
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/repo

    steps:
      - run: npm run build

      - run: ./circleci/deploy-ghpages.sh build

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test
        requires:
            - build
      - deploy
        requires:
            - test
        filters:
            branches:
              only:
                - master

